<a href="https://colab.research.google.com/github/KennJieValleser/CPE-311-CpE22S3/blob/main/Seatwork_7_2_Programming_Exercise_Data_Wrangling_with_Pandas_Part_2_Valleser.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Exercise part 4:

In [73]:
import pandas as pd
meteorite = pd.read_csv("Meteorite_Landings.csv")
meteorite.head()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,01/01/1880 12:00:00 AM,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,01/01/1951 12:00:00 AM,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,01/01/1952 12:00:00 AM,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,01/01/1976 12:00:00 AM,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,01/01/1902 12:00:00 AM,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [74]:
meteorite['year'] = meteorite['year'].str.slice(6,10)
meteorite.head()

,name,id,nametype,recclass,mass (g),fall,year,reclat,reclong,GeoLocation
0,Aachen,1,Valid,L5,21.0,Fell,1880,50.77500,6.08333,"(50.775, 6.08333)"
1,Aarhus,2,Valid,H6,720.0,Fell,1951,56.18333,10.23333,"(56.18333, 10.23333)"
2,Abee,6,Valid,EH4,107000.0,Fell,1952,54.21667,-113.00000,"(54.21667, -113.0)"
3,Acapulco,10,Valid,Acapulcoite,1914.0,Fell,1976,16.88333,-99.90000,"(16.88333, -99.9)"
4,Achiras,370,Valid,L6,780.0,Fell,1902,-33.16667,-64.95000,"(-33.16667, -64.95)"

In [75]:
meteorite['year'] = meteorite['year'].apply(pd.to_numeric)
meteorite.dtypes

name            object
id               int64
nametype        object
recclass        object
mass (g)       float64
fall            object
year           float64
reclat         float64
reclong        float64
GeoLocation     object
dtype: object

In [76]:
meteorite=meteorite[(meteorite['year'] >= 2005) & (meteorite['year'] <= 2009)]
year = meteorite['year'].unique()
print(year)

[2008. 2009. 2006. 2007. 2005.]

In [77]:
meteorite.set_index('year').head()

,name,id,nametype,recclass,mass (g),fall,reclat,reclong,GeoLocation
year,,,,,,,,,
2008.0,Almahata Sitta,48915,Valid,Ureilite-an,3950.0,Fell,20.74575,32.41275,"(20.74575, 32.41275)"
2009.0,Ash Creek,48954,Valid,L6,9500.0,Fell,31.80500,-97.01000,"(31.805, -97.01)"
2006.0,Bassikounou,44876,Valid,H5,29560.0,Fell,15.78333,-5.90000,"(15.78333, -5.9)"
2008.0,Berduc,48975,Valid,L6,270.0,Fell,-31.91000,-58.32833,"(-31.91, -58.32833)"
2007.0,Bunburra Rockhole,48653,Valid,Eucrite,324.0,Fell,-31.35000,129.19000,"(-31.35, 129.19)"

In [78]:
column1 = meteorite.groupby(['year', 'fall'])['mass (g)'].quantile(0.95)
column1

year    fall
2005.0  Found      4500.00
2006.0  Fell      25008.00
        Found      1600.50
2007.0  Fell      89675.00
        Found      1126.90
2008.0  Fell     106000.00
        Found      2274.80
2009.0  Fell       8333.40
        Found      1397.25
Name: mass (g), dtype: float64

In [79]:
column2 = meteorite.groupby(['year', 'fall'])['mass (g)'].count()
column2

year    fall
2005.0  Found     874
2006.0  Fell        5
        Found    2450
2007.0  Fell        8
        Found    1181
2008.0  Fell        9
        Found     948
2009.0  Fell        5
        Found    1492
Name: mass (g), dtype: int64

In [80]:
#1
column1 = column1.to_frame()

column1["counts"] = column2
column1

               mass (g)  counts
year   fall
2005.0 Found    4500.00     874
2006.0 Fell    25008.00       5
       Found    1600.50    2450
2007.0 Fell    89675.00       8
       Found    1126.90    1181
2008.0 Fell   106000.00       9
       Found    2274.80     948
2009.0 Fell     8333.40       5
       Found    1397.25    1492

In [81]:
#2
meteorite.groupby("fall")["mass (g)"].describe()

,count,mean,std,min,25%,50%,75%,max
fall,,,,,,,,
Fell,27.0,19029.665185,34081.623779,18.41,410.0,3950.0,8206.5,110000.0
Found,6945.0,1573.986245,42020.893987,0.00,7.5,34.5,197.0,3000000.0

##Exercise Part 5:

In [61]:
import pandas as pd
taxi = pd.read_csv("2019_Yellow_Taxi_Trip_Data.csv")
taxi.head()

,vendorid,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,ratecodeid,store_and_fwd_flag,pulocationid,dolocationid,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,2,2019-10-23T16:39:42.000,2019-10-23T17:14:10.000,1,7.93,1,N,138,170,1,29.5,1.0,0.5,7.98,6.12,0.3,47.90,2.5
1,1,2019-10-23T16:32:08.000,2019-10-23T16:45:26.000,1,2.00,1,N,11,26,1,10.5,1.0,0.5,0.00,0.00,0.3,12.30,0.0
2,2,2019-10-23T16:08:44.000,2019-10-23T16:21:11.000,1,1.36,1,N,163,162,1,9.5,1.0,0.5,2.00,0.00,0.3,15.80,2.5
3,2,2019-10-23T16:22:44.000,2019-10-23T16:43:26.000,1,1.00,1,N,170,163,1,13.0,1.0,0.5,4.32,0.00,0.3,21.62,2.5
4,2,2019-10-23T16:45:11.000,2019-10-23T16:58:49.000,1,1.96,1,N,163,236,1,10.5,1.0,0.5,0.50,0.00,0.3,15.30,2.5

In [62]:
taxi["tpep_dropoff_datetime"] = pd.to_datetime(taxi["tpep_dropoff_datetime"])

In [63]:
taxi.set_index("tpep_dropoff_datetime", inplace=True)

In [64]:
taxi.index = pd.to_datetime(taxi.index)

In [69]:
taxi['hour'] = taxi.index.hour
copytaxi = taxi.groupby('hour')[['trip_distance', 'fare_amount', 'tolls_amount', 'tip_amount']].sum()

In [70]:
fivetaxi = copytaxi["tip_amount"].nlargest(5)
fivetaxi

hour
16    12249.32
17    12044.03
18     1907.64
15       75.10
19       25.74
Name: tip_amount, dtype: float64